### ISSUE TITLE
Search through subgroups in Gitlab

### ISSUE THREAD

**Issue by jdpribula** [lindell/multi-gitter#130]
Hello,

This tool is awesome and I love it. One thing I noticed is that when using ``-G`` with Gitlab it won't find any subgroups under the one specified in the command so you have to run the tool multiple times for each location. A way to wildcard or search through subgroups would be awesome.

Example:
``multi-gitter run ./somescript.sh -G my/cool/path/``
won't find 
``my/cool/path/subgroup1/targetproject1``
``my/cool/path/subgroup2/targetproject2``

Maybe another option would to be able to wildcard projects like ``targetproject*``

**Comment by lindell** [comment]
Hello and thanks for the ticket 🙂 

It seems that the reason for this is that the default value for listing subgroup projects is `false`.
https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects

I don't think the GitLab API provides a way to use wildcards when searching for repos. If you know of it, please let me know. Otherwise, a `--include-subgroups` flag will maybe solve the problem?

**Comment by jdpribula** [comment]
A flag would be perfect.

**Comment by lindell** [comment]
Included in the new [v0.26.0](https://github.com/lindell/multi-gitter/releases/tag/v0.26.0) release 🙂
