### ISSUE TITLE
Ability to specify pull request assignees

### ISSUE THREAD

**Issue by Sam13** [lindell/multi-gitter#194]
I think it would be a good enhancement to optionally specify pull request assignees (and not just reviewers).

**Comment by Berreek** [comment]
I would like to take this one. 

However for GitHub I do not see the option to set assignees trough API (unless I'm missing something really obvious there). Rest of providers are fine as far as I saw.

**Comment by lindell** [comment]
I took a look as well @Berreek. And as you said, there exists nothing under the obvious place of [pull request operations](https://pkg.go.dev/github.com/google/go-github/v39/github#PullRequestsService).

But I think where you add it is under "add assignees to issue" since pull requests are treated as a special kind of issue in GitHub. 
https://pkg.go.dev/github.com/google/go-github/v39/github#IssuesService.AddAssignees

I have not confirmed this yet, but I'm pretty certain it's the operation to use.
