### ISSUE TITLE
Feature request: Draft PR -> Ready For Review

### ISSUE THREAD

**Issue by taylorperkins** [lindell/multi-gitter#455]
**The feature request**
When an existing PR exists and the `--draft` flag is _not_ present in the run command (or perhaps this needs to be a new command?), update the existing PR from "Draft" to "Ready For Review"

**My use case**
The `--draft` flag on the `run` command is a great feature, especially when you do not want to bug other teammates before a change has gone through CI/CD stuff. However, I am not sure of an existing way for multi-gitter to update the state of the draft PRs to "Ready For Review", specifically for PRs that have a good status.

**Implementation**

- [ ] I would like to contribute this feature if it's a suitable addition to multi-gitter
- [X] I have no intention of adding this feature myself.
 - Sorry - I'm a python/scala/scripting guy

**Comment by lindell** [comment]
I think this PR #368 might partly add this feature. But with the side-effect or re-running the script. It might be a good idea to enable just the updating as well.

**Comment by Etienne-M** [comment]
> I think this PR https://github.com/lindell/multi-gitter/pull/368 might partly add this feature. But with the side-effect or re-running the script. It might be a good idea to enable just the updating as well.

@lindell Is there any interest in supporting this in the future? I could take a look at it if there's appetite to include this feature in the repo. Did you think of what the CLI commands/options would look like?

**Comment by lindell** [comment]
@Etienne-M I would be interested in merging a PR to add this support.

After checking #368 again. It seems that draft was missed from that update, but should be a 1 line PR to add it since it's already sent with the `scm.NewPullRequest` struct.

But after that, we should add a new command, probably `multi-gitter update`, that basically only calls into the new `versionController.UpdatePullRequest` function added in #368 for each PR.
